//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScenarioEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScenarioEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 추가.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 명령어 추가.
        /// </summary>
        public static string AddCmd {
            get {
                return ResourceManager.GetString("AddCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 첫 하위 명령어 추가.
        /// </summary>
        public static string AddFirstChildCmd {
            get {
                return ResourceManager.GetString("AddFirstChildCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 첫 장면 추가.
        /// </summary>
        public static string AddFirstScene {
            get {
                return ResourceManager.GetString("AddFirstScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 다음 명령어 추가.
        /// </summary>
        public static string AddNextCmd {
            get {
                return ResourceManager.GetString("AddNextCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 다음 장면 추가.
        /// </summary>
        public static string AddNextScene {
            get {
                return ResourceManager.GetString("AddNextScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 취소.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 명령어.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 디버그.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 삭제.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 명령어 삭제.
        /// </summary>
        public static string DeleteCmd {
            get {
                return ResourceManager.GetString("DeleteCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 장면 삭제.
        /// </summary>
        public static string DeleteScene {
            get {
                return ResourceManager.GetString("DeleteScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설명.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아래로 이동.
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 편집.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 명령어 편집.
        /// </summary>
        public static string EditCmd {
            get {
                return ResourceManager.GetString("EditCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 대사 편집.
        /// </summary>
        public static string EditLines {
            get {
                return ResourceManager.GetString("EditLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 장면 편집.
        /// </summary>
        public static string EditScene {
            get {
                return ResourceManager.GetString("EditScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택지 편집.
        /// </summary>
        public static string EditSwitchCase {
            get {
                return ResourceManager.GetString("EditSwitchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택지는 최소 {0}개부터 입니다..
        /// </summary>
        public static string ErrDeleteCaseUnderMin {
            get {
                return ResourceManager.GetString("ErrDeleteCaseUnderMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 장면은 최소 {0}개부터 입니다..
        /// </summary>
        public static string ErrDeleteSceneUnderMin {
            get {
                return ResourceManager.GetString("ErrDeleteSceneUnderMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialize 실패.
        /// </summary>
        public static string ErrDeserialize {
            get {
                return ResourceManager.GetString("ErrDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택지는 최대 {0}개까지 입니다..
        /// </summary>
        public static string ErrInsertCaseOverMax {
            get {
                return ResourceManager.GetString("ErrInsertCaseOverMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 명령어 삽입 실패 : cmd is null.
        /// </summary>
        public static string ErrInsertCmdNullCmd {
            get {
                return ResourceManager.GetString("ErrInsertCmdNullCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 명령어 삽입 실패 : 유효하지 않은 index({0}), max({1}).
        /// </summary>
        public static string ErrInsertCmdOverMax {
            get {
                return ResourceManager.GetString("ErrInsertCmdOverMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 명령어 삽입 실패 : 유효하지 않은 index({0}), min({1}).
        /// </summary>
        public static string ErrInsertCmdUnderMin {
            get {
                return ResourceManager.GetString("ErrInsertCmdUnderMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 장면 삽입 실패 : scene is null.
        /// </summary>
        public static string ErrInsertSceneNullScene {
            get {
                return ResourceManager.GetString("ErrInsertSceneNullScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 장면 삽입 실패 : 유효하지 않은 index({0}), max({1}).
        /// </summary>
        public static string ErrInsertSceneOverMax {
            get {
                return ResourceManager.GetString("ErrInsertSceneOverMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 장면 삽입 실패 : 유효하지 않은 index({0}), min({1}).
        /// </summary>
        public static string ErrInsertSceneUnderMin {
            get {
                return ResourceManager.GetString("ErrInsertSceneUnderMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 잘못된 명령어입니다..
        /// </summary>
        public static string ErrInvalidCmdType {
            get {
                return ResourceManager.GetString("ErrInvalidCmdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 캐릭터를 찾을 수 없습니다..
        /// </summary>
        public static string ErrNotFoundCharacter {
            get {
                return ResourceManager.GetString("ErrNotFoundCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 명령어의 상위 장면/명령어를 찾을 수 없습니다..
        /// </summary>
        public static string ErrNotFoundCmdOwner {
            get {
                return ResourceManager.GetString("ErrNotFoundCmdOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시나리오를 찾을 수 없습니다..
        /// </summary>
        public static string ErrNotFoundScenario {
            get {
                return ResourceManager.GetString("ErrNotFoundScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 장면을 찾을 수 없습니다..
        /// </summary>
        public static string ErrNotFoundScene {
            get {
                return ResourceManager.GetString("ErrNotFoundScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설정창을 찾을 수 없습니다..
        /// </summary>
        public static string ErrNotFoundSettings {
            get {
                return ResourceManager.GetString("ErrNotFoundSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 에러.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialize 실패.
        /// </summary>
        public static string ErrSerialize {
            get {
                return ResourceManager.GetString("ErrSerialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시스템 오류.
        /// </summary>
        public static string ErrSysError {
            get {
                return ResourceManager.GetString("ErrSysError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string FindPath {
            get {
                return ResourceManager.GetString("FindPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (선택지를 입력해주세요).
        /// </summary>
        public static string GuideCase {
            get {
                return ResourceManager.GetString("GuideCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (캐릭터 파일 경로를 설정해주세요).
        /// </summary>
        public static string GuideFindPath {
            get {
                return ResourceManager.GetString("GuideFindPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 한줄 최대 글자수 {0}.
        /// </summary>
        public static string GuideHowToInputDescription {
            get {
                return ResourceManager.GetString("GuideHowToInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 한줄 최대 글자수 {0}, 라인엔딩 최대 갯수 {1}.
        /// </summary>
        public static string GuideHowToInputLines {
            get {
                return ResourceManager.GetString("GuideHowToInputLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (대사를 입력해주세요).
        /// </summary>
        public static string GuideLines {
            get {
                return ResourceManager.GetString("GuideLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택지는 최소 {0}개, 최대 {1}개.
        /// </summary>
        public static string GuideNumOfCase {
            get {
                return ResourceManager.GetString("GuideNumOfCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (장면 설명을 입력해주세요).
        /// </summary>
        public static string GuideSceneDescription {
            get {
                return ResourceManager.GetString("GuideSceneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 캐릭터 파일 경로.
        /// </summary>
        public static string LabelCharacterFilePath {
            get {
                return ResourceManager.GetString("LabelCharacterFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시나리오.
        /// </summary>
        public static string Scenario {
            get {
                return ResourceManager.GetString("Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 장면.
        /// </summary>
        public static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설정.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 위로 이동.
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 불러온 파일입니다. 그래도 다시 불러올까요?.
        /// </summary>
        public static string WarnAlreadyImportedFile {
            get {
                return ResourceManager.GetString("WarnAlreadyImportedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시나리오({0}) 편집을 종료하시겠습니까?.
        /// </summary>
        public static string WarnDeleteScenario {
            get {
                return ResourceManager.GetString("WarnDeleteScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 장면({0})을 삭제하시겠습니까?.
        /// </summary>
        public static string WarnDeleteScene {
            get {
                return ResourceManager.GetString("WarnDeleteScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 경고.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시나리오 에디터.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
