//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharacterEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CharacterEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 추가.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (이미지).
        /// </summary>
        public static string CImageGuideText {
            get {
                return ResourceManager.GetString("CImageGuideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기본얼굴.
        /// </summary>
        public static string CImageLabel {
            get {
                return ResourceManager.GetString("CImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 최소 {0}글자, 최대 {1}글자.
        /// </summary>
        public static string CNameGuideText {
            get {
                return ResourceManager.GetString("CNameGuideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이름.
        /// </summary>
        public static string CNameLabel {
            get {
                return ResourceManager.GetString("CNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 삭제.
        /// </summary>
        public static string DelButton {
            get {
                return ResourceManager.GetString("DelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 편집.
        /// </summary>
        public static string EditorTabHeader {
            get {
                return ResourceManager.GetString("EditorTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이미 열린 파일입니다..
        /// </summary>
        public static string ErrAlreadyImportedFile {
            get {
                return ResourceManager.GetString("ErrAlreadyImportedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;을(를) 찾을 수 없습니다..
        /// </summary>
        public static string ErrCharacterNotFound {
            get {
                return ResourceManager.GetString("ErrCharacterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 삭제할 캐릭터를 선택해주세요..
        /// </summary>
        public static string ErrCharacterToDeleteIsNull {
            get {
                return ResourceManager.GetString("ErrCharacterToDeleteIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터 로드 실패.
        /// </summary>
        public static string ErrDeserialize {
            get {
                return ResourceManager.GetString("ErrDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 에러.
        /// </summary>
        public static string ErrMsgBoxTitle {
            get {
                return ResourceManager.GetString("ErrMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이름의 최대 길이는 {0}입니다..
        /// </summary>
        public static string ErrOverMaxLengthCName {
            get {
                return ResourceManager.GetString("ErrOverMaxLengthCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 캐릭터 최대 개수({0})를 넘을 수 없습니다..
        /// </summary>
        public static string ErrOverMaxNumCharacter {
            get {
                return ResourceManager.GetString("ErrOverMaxNumCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 데이터 저장 실패.
        /// </summary>
        public static string ErrSerialize {
            get {
                return ResourceManager.GetString("ErrSerialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 시스템 오류.
        /// </summary>
        public static string ErrSysError {
            get {
                return ResourceManager.GetString("ErrSysError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이름의 최소 길이는 {0}입니다..
        /// </summary>
        public static string ErrUnderMinLengthCName {
            get {
                return ResourceManager.GetString("ErrUnderMinLengthCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 내보내기 경로.
        /// </summary>
        public static string ExportPathLabel {
            get {
                return ResourceManager.GetString("ExportPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 찾기.
        /// </summary>
        public static string FindButton {
            get {
                return ResourceManager.GetString("FindButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 가져오기 경로.
        /// </summary>
        public static string ImportPathLabel {
            get {
                return ResourceManager.GetString("ImportPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 저장.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 경로설정.
        /// </summary>
        public static string SetPathButton {
            get {
                return ResourceManager.GetString("SetPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설정.
        /// </summary>
        public static string SettingTabHeader {
            get {
                return ResourceManager.GetString("SettingTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 경고.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 캐릭터 에디터.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
